// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
 /* tslint:disable */
let _VERSION = '0.0.1-SNAPSHOT'; // This value will be overwritten by Webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by Webpack
let _SERVER_API_URL = ''; // This value will be overwritten by Webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
/* @toreplace SERVER_API_URL */
/* tslint:enable */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
export const SERVER_API_URL = _SERVER_API_URL;
export const PRICE_BATTERIES_INCLUDED = 0.5;
export const PRICE_PER_KILOMETER_PER_KM = 1;
export const ORDER_DELIVERY_ORIGIN = {lat: 51.055410, lng: 4.490185};
export const VAT_NUMBER = 'BE 71 7332 4014 6811 4';
